== vehicles-project
vehicles-project is an Ansible playbook for downloading a zip file from a URI containing csv files, importing those csv files into postgresql automatically inside of a Vagrant VM, and making those csv files available via a REST API using a simgple clojure program.

=== License
The MIT License (MIT).  See LICENSE.adoc

=== What is needed to run the program
You must have Ansible, VirtualBox, and Vagrant installed. See DEPENDENCIES.adoc 
As provided, the Vagrant VM will use all of your cores and 1 Gigabyte of your memory.

=== How to run
.To get this project working, perform the minimum steps:
----
 $ vagrant up 
 $ ansible-playbook vehicles.yml
----
The above opens up a compojure app on localhost port 3000
To see results point your browser to http://localhost:3000/api/vehicles
The project merges https://github.com/yencarnacion/vehicles and https://github.com/yencarnacion/zipWithCsvToPostgresVM into one project.
 

=== Notes
The first time you run "vagrant up" it will take longer than subsequent times as it will download an Ubuntu base VM. So, be patient!

If there isn't enough memory for the Vagrant VM to process your csv files, the Ansible script may exit without finishing.  In that case, you will need to manually modify the Vagrantfile so that enough memory is allocated for the Vagrant VM.

By default the Ansible playbook downloads the sample zip file contained in http://www.webninjapr.com/data/vehicles.csv.zip which is from http://catalog.data.gov/dataset/fuel-economy-data-c6a4c . The zip file contains a single csv (vehicles.csv) with fuel economy data from the Department of energy as was available on June 21, 2015.  It is licensed under http://opendefinition.org/licenses/cc-by-sa/[Creative Commons Attribution Share-Alike].  The Postgresql table that is created is called +vehicles+.

The name of your csv files will be the name of your tables.  For example, the vehicles.csv file becomes table +vechicles+.

The postgresql version used is 9.3.
 
=== Other
This playbook uses the role from https://github.com/nickjj/ansible-postgres with the MIT License.

