---
# file: oracle-java/meta/main.yml
#
# meta file
#
galaxy_info:
  author: Pedro Salgado
  description: Role to install Oracle Java.
  company: ansiblebit.org
  license: BSD
  min_ansible_version: 1.9.3
  platforms:
    - name: CentOS
      versions:
        - all
        - any
        - 7
        - 6
    - name: Debian
      versions:
        - jessie
        - wheezy
    - name: MacOSX
      versions:
        - 10.10.2
        - 10.10.1
        - 10.9.5
        - 10.9.4
        - 10.9.3
        - 10.9.2
        - 10.9.1
    - name: RedHat
      versions:
        - all
        - any
        - 7
        - 6
    - name: Ubuntu
      versions:
        - vivid
        - trusty
        - precise
  categories:
    - development
    - system
dependencies:
  - role: ansiblebit.launchpad-ppa-webupd8
    when: (ansible_distribution | lower == 'debian') or (ansible_distribution | lower == 'ubuntu')
